sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

install:
  - go get -u github.com/alecthomas/gometalinter
  - go get -t -v ./...

before_script:
  - gometalinter --force --install

script:
  - go test .
  - gometalinter --deadline=10m --disable="gocyclo" -e"lint\.go" -e"lint_test\.go" .

matrix:
  allow_failures:
    - go: master
  fast_finish: true
